/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2025-03-14 11:59:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.Map;
import java.util.List;
import ucl.ac.uk.main.Folder;
import ucl.ac.uk.main.Note;

public final class indexList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("ucl.ac.uk.main.Note");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("ucl.ac.uk.main.Folder");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Note Taking App</title>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/meta.jsp", out, false);
      out.write("\n");
      out.write("    <style>\n");
      out.write("        .scrollable-list {\n");
      out.write("            max-height: 30vh; /*30% of the page*/\n");
      out.write("            overflow-y: auto; /*scrollable if too many notes*/\n");
      out.write("        }\n");
      out.write("        .button-container {\n");
      out.write("            display: inline-flex;\n");
      out.write("            gap: 10px; /* Adjust spacing */\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("    ");

        String title = (String) request.getAttribute("title");
        Folder currentFolder = (Folder) request.getAttribute("currentFolder");
    
      out.write("\n");
      out.write("\n");
      out.write("    <h1>");
      out.print( title );
      out.write("</h1>\n");
      out.write("\n");
      out.write("    <form method=\"get\" action=\"displayIndex\">\n");
      out.write("\n");
      out.write("        <input type=\"hidden\" name=\"folderId\" value=\"");
      out.print( currentFolder.getId() );
      out.write("\">\n");
      out.write("\n");
      out.write("        <label for=\"sort\">Sort By:</label>\n");
      out.write("        <select class=\"form-select\" name=\"sort\" id=\"sort\">\n");
      out.write("            <option value=\"alpha\">Alphabetical</option>\n");
      out.write("            <option value=\"newest\">Newest to Oldest</option>\n");
      out.write("            <option value=\"oldest\">Oldest to Newest</option>\n");
      out.write("        </select>\n");
      out.write("        <button type=\"submit\" class=\"btn btn-primary btn-sm\">Sort</button>\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    <h3>Folders</h3>\n");
      out.write("    <ul class=\"list-group\">\n");
      out.write("        ");

            if (currentFolder != null) {
                // Display subfolders
                List<Folder> sortedSubfolders = (List<Folder>) request.getAttribute("sortedFolders");
                if (!sortedSubfolders.isEmpty()) {
                    for (Folder subfolder : sortedSubfolders) {
        
      out.write("\n");
      out.write("                        <li class=\"list-group-item\">\n");
      out.write("                            <p><a href=\"displayIndex?folderId=");
      out.print( subfolder.getId() );
      out.write('"');
      out.write('>');
      out.print( subfolder.getName() );
      out.write("</a></p>\n");
      out.write("                            <p>Created: ");
      out.print( subfolder.getDateTime() );
      out.write("</p>\n");
      out.write("\n");
      out.write("                            <form action=\"deleteFolder\" method=\"post\" style=\"display:inline;\">\n");
      out.write("                                <input type=\"hidden\" name=\"folderId\" value=\"");
      out.print( subfolder.getId() );
      out.write("\">\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-danger btn-sm\">Delete</button>\n");
      out.write("                            </form>\n");
      out.write("                        </li>\n");
      out.write("        ");
          }
                } else {
        
      out.write("\n");
      out.write("                    <p>This folder does not have subfolders</p>\n");
      out.write("        ");
      } 
      out.write("\n");
      out.write("    </ul>\n");
      out.write("\n");
      out.write("    <h3>Notes</h3>\n");
      out.write("    <ul class=\"list-group scrollable-list\"\">\n");
      out.write("        ");

                // Display notes
                List<Note> sortedNotes = (List<Note>) request.getAttribute("sortedNotes");
                if (!sortedNotes.isEmpty()) {
                    for (Note note : sortedNotes) {
        
      out.write("\n");
      out.write("                        <li class=\"list-group-item\">\n");
      out.write("                            <p><a href=\"displayNote?noteId=");
      out.print( note.getId() );
      out.write('"');
      out.write('>');
      out.print( note.getName() );
      out.write("</a></p>\n");
      out.write("                            <p>Created: ");
      out.print( note.getDateTime() );
      out.write("</p>\n");
      out.write("\n");
      out.write("                            <form action=\"editNote\" method=\"post\" style=\"display:inline;\">\n");
      out.write("                                <input type=\"hidden\" name=\"noteId\" value=\"");
      out.print( note.getId() );
      out.write("\">\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-info btn-sm\">Edit</button>\n");
      out.write("                            </form>\n");
      out.write("\n");
      out.write("                            <form action=\"deleteNote\" method=\"post\" style=\"display:inline;\">\n");
      out.write("                                <input type=\"hidden\" name=\"noteId\" value=\"");
      out.print( note.getId() );
      out.write("\">\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-danger btn-sm\">Delete</button>\n");
      out.write("                            </form>\n");
      out.write("                        </li>\n");
      out.write("        ");
          }
                } else {
        
      out.write("\n");
      out.write("                    <p>This folder does not have notes</p>\n");
      out.write("        ");

                }
            }
        
      out.write("\n");
      out.write("    </ul>\n");
      out.write("\n");
      out.write("    <div class=\"button-container\">\n");
      out.write("        <div class=\"dropdown\">\n");
      out.write("            <button class=\"btn btn-success\" type=\"button\" data-toggle=\"dropdown\">\n");
      out.write("                <span class=\"glyphicon glyphicon-plus\"></span> Add\n");
      out.write("            </button>\n");
      out.write("            <ul class=\"dropdown-menu\">\n");
      out.write("                <li><a href=\"addItem?folderId=");
      out.print( currentFolder.getId() );
      out.write("&itemType=note\">Add Note</a></li>\n");
      out.write("                <li><a href=\"addItem?folderId=");
      out.print( currentFolder.getId() );
      out.write("&itemType=folder\">Add Folder</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        ");

            if (currentFolder.getParentId() != null) {
        
      out.write("\n");
      out.write("                <a href=\"displayIndex?folderId=");
      out.print(currentFolder.getParentId());
      out.write("\" class=\"btn btn-primary\">Back</a>\n");
      out.write("        ");
  } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
